*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE /CADAXO/LSQLCSYMBTOP.              " Global Data
  INCLUDE /CADAXO/LSQLCSYMBUXX.              " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE /CADAXO/LSQLCSYMBF00                    . " subprograms
  INCLUDE /CADAXO/LSQLCSYMBI00                    . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE /CADAXO/LSQLCSYMBF...              " Subprograms
* INCLUDE /CADAXO/LSQLCSYMBO...              " PBO-Modules
* INCLUDE /CADAXO/LSQLCSYMBI...              " PAI-Modules

INCLUDE /CADAXO/LSQLCSYMBF01.
