*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*   generation date: 11.04.2010 at 17:15:55 by user CADAXO
*   view maintenance generator version: #001407#
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE /CADAXO/LSQLCVGRVTOP.              " Global Data
  INCLUDE /CADAXO/LSQLCVGRVUXX.              " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE /CADAXO/LSQLCVGRVF00                    . " subprograms
  INCLUDE /CADAXO/LSQLCVGRVI00                    . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE /CADAXO/LSQLCVGRVF...              " Subprograms
* INCLUDE /CADAXO/LSQLCVGRVO...              " PBO-Modules
* INCLUDE /CADAXO/LSQLCVGRVI...              " PAI-Modules

INCLUDE /CADAXO/LSQLCVGRVF01.
