*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: /CADAXO/SQLCTEMV................................*
FORM GET_DATA_/CADAXO/SQLCTEMV.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /CADAXO/SQLCTEMP WHERE
(VIM_WHERETAB) .
    CLEAR /CADAXO/SQLCTEMV .
/CADAXO/SQLCTEMV-CLIENT =
/CADAXO/SQLCTEMP-CLIENT .
/CADAXO/SQLCTEMV-TEMPLATE_NAME =
/CADAXO/SQLCTEMP-TEMPLATE_NAME .
/CADAXO/SQLCTEMV-TEMPLATE_CLASS =
/CADAXO/SQLCTEMP-TEMPLATE_CLASS .
/CADAXO/SQLCTEMV-FLAG_ACTIVE =
/CADAXO/SQLCTEMP-FLAG_ACTIVE .
    SELECT SINGLE * FROM /CADAXO/SQLCTEMT WHERE
TEMPLATE_NAME = /CADAXO/SQLCTEMP-TEMPLATE_NAME AND
LANGUAGE = SY-LANGU .
    IF SY-SUBRC EQ 0.
/CADAXO/SQLCTEMV-TEMPLATE_DESC =
/CADAXO/SQLCTEMT-TEMPLATE_DESC .
    ENDIF.
<VIM_TOTAL_STRUC> = /CADAXO/SQLCTEMV.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/CADAXO/SQLCTEMV .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /CADAXO/SQLCTEMV.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/CADAXO/SQLCTEMV-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /CADAXO/SQLCTEMP WHERE
  TEMPLATE_NAME = /CADAXO/SQLCTEMV-TEMPLATE_NAME .
    IF SY-SUBRC = 0.
    DELETE /CADAXO/SQLCTEMP .
    ENDIF.
    DELETE FROM /CADAXO/SQLCTEMT WHERE
    TEMPLATE_NAME = /CADAXO/SQLCTEMP-TEMPLATE_NAME .
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /CADAXO/SQLCTEMP WHERE
  TEMPLATE_NAME = /CADAXO/SQLCTEMV-TEMPLATE_NAME .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /CADAXO/SQLCTEMP.
    ENDIF.
/CADAXO/SQLCTEMP-CLIENT =
/CADAXO/SQLCTEMV-CLIENT .
/CADAXO/SQLCTEMP-TEMPLATE_NAME =
/CADAXO/SQLCTEMV-TEMPLATE_NAME .
/CADAXO/SQLCTEMP-TEMPLATE_CLASS =
/CADAXO/SQLCTEMV-TEMPLATE_CLASS .
/CADAXO/SQLCTEMP-FLAG_ACTIVE =
/CADAXO/SQLCTEMV-FLAG_ACTIVE .
    IF SY-SUBRC = 0.
    UPDATE /CADAXO/SQLCTEMP .
    ELSE.
    INSERT /CADAXO/SQLCTEMP .
    ENDIF.
    SELECT SINGLE FOR UPDATE * FROM /CADAXO/SQLCTEMT WHERE
    TEMPLATE_NAME = /CADAXO/SQLCTEMP-TEMPLATE_NAME AND
    LANGUAGE = SY-LANGU .
      IF SY-SUBRC <> 0.   "insert preprocessing: init WA
        CLEAR /CADAXO/SQLCTEMT.
/CADAXO/SQLCTEMT-TEMPLATE_NAME =
/CADAXO/SQLCTEMP-TEMPLATE_NAME .
/CADAXO/SQLCTEMT-LANGUAGE =
SY-LANGU .
      ENDIF.
/CADAXO/SQLCTEMT-TEMPLATE_DESC =
/CADAXO/SQLCTEMV-TEMPLATE_DESC .
    IF SY-SUBRC = 0.
    UPDATE /CADAXO/SQLCTEMT .
    ELSE.
    INSERT /CADAXO/SQLCTEMT .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/CADAXO/SQLCTEMV-UPD_FLAG,
STATUS_/CADAXO/SQLCTEMV-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/CADAXO/SQLCTEMV.
  SELECT SINGLE * FROM /CADAXO/SQLCTEMP WHERE
TEMPLATE_NAME = /CADAXO/SQLCTEMV-TEMPLATE_NAME .
/CADAXO/SQLCTEMV-CLIENT =
/CADAXO/SQLCTEMP-CLIENT .
/CADAXO/SQLCTEMV-TEMPLATE_NAME =
/CADAXO/SQLCTEMP-TEMPLATE_NAME .
/CADAXO/SQLCTEMV-TEMPLATE_CLASS =
/CADAXO/SQLCTEMP-TEMPLATE_CLASS .
/CADAXO/SQLCTEMV-FLAG_ACTIVE =
/CADAXO/SQLCTEMP-FLAG_ACTIVE .
    SELECT SINGLE * FROM /CADAXO/SQLCTEMT WHERE
TEMPLATE_NAME = /CADAXO/SQLCTEMP-TEMPLATE_NAME AND
LANGUAGE = SY-LANGU .
    IF SY-SUBRC EQ 0.
/CADAXO/SQLCTEMV-TEMPLATE_DESC =
/CADAXO/SQLCTEMT-TEMPLATE_DESC .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR /CADAXO/SQLCTEMV-TEMPLATE_DESC .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/CADAXO/SQLCTEMV USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /CADAXO/SQLCTEMV-TEMPLATE_NAME TO
/CADAXO/SQLCTEMP-TEMPLATE_NAME .
MOVE /CADAXO/SQLCTEMV-CLIENT TO
/CADAXO/SQLCTEMP-CLIENT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/CADAXO/SQLCTEMP'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /CADAXO/SQLCTEMP TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/CADAXO/SQLCTEMP'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

MOVE /CADAXO/SQLCTEMP-TEMPLATE_NAME TO
/CADAXO/SQLCTEMT-TEMPLATE_NAME .
MOVE SY-LANGU TO
/CADAXO/SQLCTEMT-LANGUAGE .
MOVE /CADAXO/SQLCTEMV-CLIENT TO
/CADAXO/SQLCTEMT-CLIENT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/CADAXO/SQLCTEMT'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /CADAXO/SQLCTEMT TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/CADAXO/SQLCTEMT'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*

* base table related FORM-routines.............
INCLUDE LSVIMFTX .
