*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*   generation date: 06.04.2010 at 13:37:32 by user CADAXO
*   view maintenance generator version: #001407#
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE /CADAXO/LSQLCTEMVTOP.              " Global Data
  INCLUDE /CADAXO/LSQLCTEMVUXX.              " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE /CADAXO/LSQLCTEMVF00                    . " subprograms
  INCLUDE /CADAXO/LSQLCTEMVI00                    . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE /CADAXO/LSQLCTEMVF...              " Subprograms
* INCLUDE /CADAXO/LSQLCTEMVO...              " PBO-Modules
* INCLUDE /CADAXO/LSQLCTEMVI...              " PAI-Modules

INCLUDE /CADAXO/LSQLCTEMVF01.
