*<SCRIPT:PERSISTENT>
REPORT  /cadaxo/dbg_send_2_cockpit.

*<SCRIPT:HEADER>
*<SCRIPTNAME>/CADAXO/DBG_SEND_2_COCKPIT</SCRIPTNAME>
*<SCRIPT_CLASS>LCL_DEBUGGER_SCRIPT</SCRIPT_CLASS>
*<SCRIPT_COMMENT>Send SQL Select Statement to the Cadaxo SQL Cockpit</SCRIPT_COMMENT>
*<SINGLE_RUN>X</SINGLE_RUN>

*</SCRIPT:HEADER>

*<SCRIPT:PRESETTINGS>

*</SCRIPT:PRESETTINGS>

*<SCRIPT:SCRIPT_CLASS>
CLASS lcl_debugger_script DEFINITION INHERITING FROM /cadaxo/cl_tpda_script_class.ENDCLASS.
CLASS lcl_debugger_script IMPLEMENTATION.ENDCLASS.
*</SCRIPT:SCRIPT_CLASS>

*</SCRIPT:PERSISTENT>
