PROCESS BEFORE OUTPUT.
 MODULE detail_init.
*
PROCESS AFTER INPUT.
 MODULE DETAIL_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE DETAIL_SET_PFSTATUS.
 CHAIN.
    FIELD /CADAXO/SQLCTEMT-TEMPLATE_NAME .
    FIELD /CADAXO/SQLCTEMT-LANGUAGE .
    FIELD /CADAXO/SQLCTEMT-TEMPLATE_DESC .
  MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
 endchain.
 chain.
    FIELD /CADAXO/SQLCTEMT-TEMPLATE_NAME .
    FIELD /CADAXO/SQLCTEMT-LANGUAGE .
  module detail_pai.
 endchain.
