*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: /CADAXO/SQLCVGRV................................*
FORM GET_DATA_/CADAXO/SQLCVGRV.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /CADAXO/SQLCVGRP WHERE
(VIM_WHERETAB) .
    CLEAR /CADAXO/SQLCVGRV .
/CADAXO/SQLCVGRV-MANDT =
/CADAXO/SQLCVGRP-MANDT .
/CADAXO/SQLCVGRV-VARGROUP =
/CADAXO/SQLCVGRP-VARGROUP .
    SELECT SINGLE * FROM /CADAXO/SQLCVGRT WHERE
VARGROUP = /CADAXO/SQLCVGRP-VARGROUP AND
LANGUAGE = SY-LANGU .
    IF SY-SUBRC EQ 0.
/CADAXO/SQLCVGRV-VARGROUP_DESC =
/CADAXO/SQLCVGRT-VARGROUP_DESC .
    ENDIF.
<VIM_TOTAL_STRUC> = /CADAXO/SQLCVGRV.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/CADAXO/SQLCVGRV .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /CADAXO/SQLCVGRV.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/CADAXO/SQLCVGRV-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /CADAXO/SQLCVGRP WHERE
  VARGROUP = /CADAXO/SQLCVGRV-VARGROUP .
    IF SY-SUBRC = 0.
    DELETE /CADAXO/SQLCVGRP .
    ENDIF.
    DELETE FROM /CADAXO/SQLCVGRT WHERE
    VARGROUP = /CADAXO/SQLCVGRP-VARGROUP .
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /CADAXO/SQLCVGRP WHERE
  VARGROUP = /CADAXO/SQLCVGRV-VARGROUP .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /CADAXO/SQLCVGRP.
    ENDIF.
/CADAXO/SQLCVGRP-MANDT =
/CADAXO/SQLCVGRV-MANDT .
/CADAXO/SQLCVGRP-VARGROUP =
/CADAXO/SQLCVGRV-VARGROUP .
    IF SY-SUBRC = 0.
    UPDATE /CADAXO/SQLCVGRP .
    ELSE.
    INSERT /CADAXO/SQLCVGRP .
    ENDIF.
    SELECT SINGLE FOR UPDATE * FROM /CADAXO/SQLCVGRT WHERE
    VARGROUP = /CADAXO/SQLCVGRP-VARGROUP AND
    LANGUAGE = SY-LANGU .
      IF SY-SUBRC <> 0.   "insert preprocessing: init WA
        CLEAR /CADAXO/SQLCVGRT.
/CADAXO/SQLCVGRT-VARGROUP =
/CADAXO/SQLCVGRP-VARGROUP .
/CADAXO/SQLCVGRT-LANGUAGE =
SY-LANGU .
      ENDIF.
/CADAXO/SQLCVGRT-VARGROUP_DESC =
/CADAXO/SQLCVGRV-VARGROUP_DESC .
    IF SY-SUBRC = 0.
    UPDATE /CADAXO/SQLCVGRT .
    ELSE.
    INSERT /CADAXO/SQLCVGRT .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/CADAXO/SQLCVGRV-UPD_FLAG,
STATUS_/CADAXO/SQLCVGRV-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/CADAXO/SQLCVGRV.
  SELECT SINGLE * FROM /CADAXO/SQLCVGRP WHERE
VARGROUP = /CADAXO/SQLCVGRV-VARGROUP .
/CADAXO/SQLCVGRV-MANDT =
/CADAXO/SQLCVGRP-MANDT .
/CADAXO/SQLCVGRV-VARGROUP =
/CADAXO/SQLCVGRP-VARGROUP .
    SELECT SINGLE * FROM /CADAXO/SQLCVGRT WHERE
VARGROUP = /CADAXO/SQLCVGRP-VARGROUP AND
LANGUAGE = SY-LANGU .
    IF SY-SUBRC EQ 0.
/CADAXO/SQLCVGRV-VARGROUP_DESC =
/CADAXO/SQLCVGRT-VARGROUP_DESC .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR /CADAXO/SQLCVGRV-VARGROUP_DESC .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/CADAXO/SQLCVGRV USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /CADAXO/SQLCVGRV-VARGROUP TO
/CADAXO/SQLCVGRP-VARGROUP .
MOVE /CADAXO/SQLCVGRV-MANDT TO
/CADAXO/SQLCVGRP-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/CADAXO/SQLCVGRP'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /CADAXO/SQLCVGRP TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/CADAXO/SQLCVGRP'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

MOVE /CADAXO/SQLCVGRP-VARGROUP TO
/CADAXO/SQLCVGRT-VARGROUP .
MOVE SY-LANGU TO
/CADAXO/SQLCVGRT-LANGUAGE .
MOVE /CADAXO/SQLCVGRV-MANDT TO
/CADAXO/SQLCVGRT-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/CADAXO/SQLCVGRT'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /CADAXO/SQLCVGRT TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/CADAXO/SQLCVGRT'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
