PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_/CADAXO/SQLCJCHE CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD /CADAXO/SQLCJCHE-GUID_HEADER .
    FIELD /CADAXO/SQLCJCHE-LEFT_TABLE .
    FIELD /CADAXO/SQLCJCHE-JOIN_TYPE .
    FIELD /CADAXO/SQLCJCHE-JOINED_TABLE .
    FIELD /CADAXO/SQLCJCHE-CNT .
    FIELD /CADAXO/SQLCJCHE-LOGSYS .
    FIELD /CADAXO/SQLCJCHE-SQLCYEAR .
    FIELD /CADAXO/SQLCJCHE-SQLCMONTH .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD /CADAXO/SQLCJCHE-GUID_HEADER .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
