PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_/CADAXO/SQLCJCPO CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD /CADAXO/SQLCJCPO-GUID_HEADER .
    FIELD /CADAXO/SQLCJCPO-GUID_POSTION .
    FIELD /CADAXO/SQLCJCPO-LEFT_FIELD .
    FIELD /CADAXO/SQLCJCPO-COND .
    FIELD /CADAXO/SQLCJCPO-JOINED_FIELD .
    FIELD /CADAXO/SQLCJCPO-OPERATOR .
    FIELD /CADAXO/SQLCJCPO-CNT .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD /CADAXO/SQLCJCPO-GUID_HEADER .
    FIELD /CADAXO/SQLCJCPO-GUID_POSTION .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
